version: '3.7'

services:

  nginx:
    image: nginx:alpine
    container_name: chress-1-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - chress-1

  app:
    build:
      args:
        user: chris
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: chress-1
    container_name: chress-1-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - chress-1
  
  db:
    image: mariadb:latest
    container_name: chress-1-db
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - chress-1

networks:
  chress-1:
    driver: bridge